export const GET_ESINEET = 'GET_ESINEET';
export const ADD_ESINE = 'ADD_ESINE';
export const DELETE_ESINE = 'DELETE_ESINE';
export const ESINEET_LATAUTUU= 'ESINEET_LATAUTUU';

export const GET_PERSONS = 'GET_PERSONS';
export const ADD_PERSON = 'ADD_PERSON';
export const DELETE_PERSON = 'DELETE_PERSON';
export const PERSONS_LOADING = 'PERSONS_LOADING';


export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USED_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN:FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
